type Departamento = {
    area: number,
    unidades: number,
    recamaras: number,
    bathrooms: number,
    estacionamiento: number,
    img: string,
    section: string,
    area_terraza?: number,
    sala_comedor: boolean,
    cuarto_lavado: boolean,
    closet_lavado: boolean,
    estudio: boolean,
    plano_llave: string,
}
export const departamentos: Record<string, Departamento> = {
    A: {
        area: 75.9,
        unidades: 9,
        recamaras: 2,
        bathrooms: 2,
        estacionamiento: 2,
        section: "#departamento_a",
        img: "/depa.png",
        sala_comedor: true,
        cuarto_lavado: true,
        closet_lavado: false,
        estudio: false,
        plano_llave: "/planos_llave/PTLL-A.jpg"
    },
    B: {
        area: 82.7,
        unidades: 9,
        recamaras: 2,
        bathrooms: 2,
        estacionamiento: 2,
        section: "#departamento_b",
        img: "/depb.png",
        sala_comedor: true,
        cuarto_lavado: true,
        closet_lavado: false,
        estudio: true,
        plano_llave: "/planos_llave/PTLL-B.jpg"
    },
    C1: {
        area: 63.3,
        unidades: 9,
        recamaras: 1,
        bathrooms: 1,
        estacionamiento: 1,
        section: "#departamento_c1",
        img: "/depc1.png",
        sala_comedor: true,
        cuarto_lavado: true,
        closet_lavado: false,
        estudio: true,
        plano_llave: "/planos_llave/PTLL-C1.jpg"
    },
    C2: {
        area: 62.3,
        unidades: 9,
        recamaras: 1,
        bathrooms: 1,
        estacionamiento: 1,
        section: "#departamento_c2",
        img: "/depc2.png",
        sala_comedor: true,
        cuarto_lavado: true,
        closet_lavado: false,
        estudio: true,
        plano_llave: "/planos_llave/PTLL-C2.jpg"
    },
    C3: {
        area: 63.2,
        unidades: 9,
        recamaras: 1,
        bathrooms: 1,
        estacionamiento: 1,
        section: "#departamento_c3",
        img: "/depc3.png",
        sala_comedor: true,
        cuarto_lavado: true,
        closet_lavado: false,
        estudio: true,
        plano_llave: "/planos_llave/PTLL-C3.jpg"
    },
    D: {
        area: 59.7,
        unidades: 9,
        recamaras: 1,
        bathrooms: 1,
        estacionamiento: 1,
        section: "#departamento_d",
        img: "/depd.png",
        sala_comedor: true,
        cuarto_lavado: false,
        closet_lavado: true,
        estudio: false,
        plano_llave: "/planos_llave/PTLL-D.jpg"
    },
    E: {
        area: 81.9,
        unidades: 1,
        recamaras: 2,
        bathrooms: 2,
        estacionamiento: 2,
        section: "#departamento_d",
        img: "/depe.png",
        sala_comedor: true,
        cuarto_lavado: true,
        closet_lavado: false,
        estudio: false,
        area_terraza: 26.33,
        plano_llave: "/planos_llave/PBLL-UE.jpg"
    },
}
